### ISSUE TITLE
crash when moved via cutscene travel

### ISSUE THREAD

**Issue by neongrey** [InitialDet/MinionRoulette#3]
Not sure if you got this fixed in the last update but I had a minion out, roulette active, when I went into the cutscene in 6.3 MSQ that moves you to Tertium for the first time; got a crash that the error indicated was minion roulette. If you need more info, let me know, I should have it, I just wanted to submit this before I forgot again.

**Comment by InitialDet** [comment]
If you have a screenshot of the error it would help a lot

**Comment by neongrey** [comment]
I do not, but I managed to track the crash down in my log, text looks the same as what it gave me on the crash, here you go:

2023-01-11 21:33:10.325 -06:00 [FTL] Unhandled exception on AppDomain
System.MissingMethodException: Method not found: 'UInt32 FFXIVClientStructs.FFXIV.Client.Game.ActionManager.GetActionStatus(FFXIVClientStructs.FFXIV.Client.Game.ActionType, UInt32, Int64, UInt32, UInt32)'.
   at MinionRoulette.Plugin.MinionSwap.ActionAvailable(UInt32 id)
   at MinionRoulette.Plugin.MinionSwap.SwapMinion(UInt16 zoneID)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2023-01-11 21:33:10.326 -06:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0wMS0xMVQyMTozMzoxMC4zMjYwMTI4LTA2OjAwIiwiSW5mbyI6IlN5c3RlbS5NaXNzaW5nTWV0aG9kRXhjZXB0aW9uOiBNZXRob2Qgbm90IGZvdW5kOiAnVUludDMyIEZGWElWQ2xpZW50U3RydWN0cy5GRlhJVi5DbGllbnQuR2FtZS5BY3Rpb25NYW5hZ2VyLkdldEFjdGlvblN0YXR1cyhGRlhJVkNsaWVudFN0cnVjdHMuRkZYSVYuQ2xpZW50LkdhbWUuQWN0aW9uVHlwZSwgVUludDMyLCBJbnQ2NCwgVUludDMyLCBVSW50MzIpJy5cclxuICAgYXQgTWluaW9uUm91bGV0dGUuUGx1Z2luLk1pbmlvblN3YXAuQWN0aW9uQXZhaWxhYmxlKFVJbnQzMiBpZClcclxuICAgYXQgTWluaW9uUm91bGV0dGUuUGx1Z2luLk1pbmlvblN3YXAuU3dhcE1pbmlvbihVSW50MTYgem9uZUlEKVxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLlRhc2tzLlRhc2suPD5jLjxUaHJvd0FzeW5jPmJfXzEyOF8xKE9iamVjdCBzdGF0ZSlcclxuICAgYXQgU3lzdGVtLlRocmVhZGluZy5RdWV1ZVVzZXJXb3JrSXRlbUNhbGxiYWNrLkV4ZWN1dGUoKVxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLlRocmVhZFBvb2xXb3JrUXVldWUuRGlzcGF0Y2goKVxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLlBvcnRhYmxlVGhyZWFkUG9vbC5Xb3JrZXJUaHJlYWQuV29ya2VyVGhyZWFkU3RhcnQoKSIsIkNvbnRleHQiOiJEYWxhbXVkVW5oYW5kbGVkIn0=

**Comment by InitialDet** [comment]
The log says you got the error on 2023-01-11, when the plugin was indeed broken. did it also happen recently?

Dalamud was having some issues in the past few days, but it should be working fine in the lastest version.

**Comment by InitialDet** [comment]
Im assuming you saw this same error window https://github.com/InitialDet/MinionRoulette/issues/2

**Comment by neongrey** [comment]
aha, yes I did, all good then!
